version: '3.8'
services:
  app:
    image: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      # Собираем из текущей директории
      context: .
      # Используем Dockerfile
      dockerfile: Dockerfile