spring:

  datasource:
    url: jdbc:h2:mem:library

  flyway:
    locations: classpath:db/migration
    enabled: true

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none


logging:
  level:
    ROOT: INFO