spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: postgres

  flyway:
    locations: classpath:db/migration
    enabled: true

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none


# Включить доступные эндпоинты, предоставляющие метрики, проверку здоровья и журнал логов
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logs

  endpoint:
    health:
      show-details: always

  health:
    diskspace:
      enabled: false
    db:
      enabled: false
    ping:
      enabled: false


logging:
  file:
    name: app.log

  level:
    root: INFO